version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./defaults/templates:/etc/nginx/templates
      - ./defaults/nginx.conf:/etc/nginx/nginx.conf
      - ./defaults/proxy.conf:/etc/nginx/proxy.conf
      - ./.sync:/sync:ro
    ports:
      - "80:80"
    networks:
      - artemis-net


  saml:
    image: jamedjo/test-saml-idp
    hostname: saml
    ports:
      - "9980:8080"
    volumes:
      - ./saml/saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php
      - ./saml/config.php:/var/www/simplesamlphp/config/config.php
    networks:
      - artemis-net    

  gitlab:
    build:
      context: ./docker/gitlab
    restart: unless-stopped
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_HTTPS_PORT}:443"
      - "${GITLAB_SSH_PORT}:22"
    environment:
      - GITLAB_OMNIBUS_CONFIG=prometheus_monitoring['enable'] = false; nginx['listen_port'] = 80; gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']
    networks:
      - artemis-net

  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    user: root
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/bin/com.docker.cli:/usr/bin/com.docker.cli:ro
    ports:
      - "50000:50000"
      - "${JENKINS_HTTP_PORT}:8080"
    networks:
      - artemis-net


  artemis-be:
    build:
      context: ./docker/artemis-server
      args:
        ARTEMIS_VERSION: ${ARTEMIS_VERSION}
    restart: unless-stopped
    depends_on:
      - artemis-db
      - gitlab
      - jenkins
    volumes:
      - ./data/artemis-be/config:/opt/Artemis/config
      - ./data/artemis-be/data:/opt/Artemis/data
      - ./.sync:/opt/Artemis/sync
    environment:
      - WAIT_FOR="gitlab:80"
      - PROFILES=${PROFILES}
      - SPRING_DATASOURCE_URL=jdbc:mysql://artemis-db:3306/Artemis?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    networks:
      - artemis-net

  artemis-db:
    image: mysql:8.0.23
    restart: unless-stopped
    volumes:
      - ./data/artemis-db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=Artemis
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    networks:
      - artemis-net
    cap_add:
      - SYS_NICE

  artemis-fe:
    build:
      context: ./docker/artemis-client
      args:
        ARTEMIS_VERSION: ${ARTEMIS_VERSION}
    restart: unless-stopped
    depends_on:
      - artemis-be
    volumes:
      - ${CUSTOM_PRIVACY_STATEMENT}:/usr/share/nginx/html/public/content/privacy_statement.html:ro
      - ${CUSTOM_IMPRINT}:/usr/share/nginx/html/public/content/imprint.html:ro
      - ${CUSTOM_ABOUT}:/usr/share/nginx/html/public/content/about-us.json:ro
    environment:
      - SERVER_NAME=localhost
    networks:
      - artemis-net


networks:
  artemis-net:

