services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./defaults/templates:/etc/nginx/templates
      - ./defaults/nginx.conf:/etc/nginx/nginx.conf
      - ./defaults/proxy.conf:/etc/nginx/proxy.conf
    depends_on:
      artemis:
        condition: service_started
      gitlab:
        condition: service_started
      jenkins:
        condition: service_started
    ports:
      - "80:80"
    networks:
      - artemis-net

  saml:
    image: jamedjo/test-saml-idp
    hostname: saml
    ports:
      - "9980:8080"
    volumes:
      - ./saml/saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php
      - ./saml/config.php:/var/www/simplesamlphp/config/config.php
    networks:
      - artemis-net  

  gitlab:
    build:
      context: ./docker/gitlab
      args:
          GITLAB_VERSION: ${GITLAB_VERSION}
    restart: unless-stopped
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"
    environment:
      - GITLAB_OMNIBUS_CONFIG=prometheus_monitoring['enable'] = false; nginx['listen_port'] = 80; gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']
    networks:
      - artemis-net

  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    user: root
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/bin/com.docker.cli:/usr/bin/com.docker.cli:ro
    ports:
      - "50000:50000"
      - "${JENKINS_HTTP_PORT}:8080"
    networks:
      - artemis-net

  artemis:
    image: ghcr.io/ls1intum/artemis:${ARTEMIS_VERSION}
    restart: unless-stopped
    depends_on:
      artemis-db:
        condition: service_started
      gitlab:
        condition: service_healthy
      jenkins:
        condition: service_started
    volumes:
      - ./data/artemis-be/config:/opt/artemis/config
      - ./data/artemis-be/data:/opt/artemis/data
      - ./branding:/opt/artemis/public/content:ro
    environment:
      - spring.profiles.active=${PROFILES}
      - SPRING_DATASOURCE_URL=jdbc:mysql://artemis-db:3306/Artemis?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    networks:
      - artemis-net

  artemis-db:
    image: mysql:8.0.23
    restart: unless-stopped
    volumes:
      - ./data/artemis-db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=Artemis
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
    networks:
      - artemis-net
    cap_add:
      - SYS_NICE

networks:
  artemis-net:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
